spring.application.name=demo
server.port=8080



properties spring.data.mongodb.host=localhost spring.data.mongodb.port=27017 spring.data.mongodb.database=neurofleet
spring.data.mongodb.database=neurofleetx

spring.main.allow-circular-references=true
jwt.secret=neurofleetxSecretKeyneurofleetxSecretKey
jwt.expirationMs=86400000
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration